config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end

  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]


  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/views/courses/index.html.erb
<br />

<div class = "booyah-box col-xs-10 col-xs-offset-1">
  <h1 class = "text-center">Try something new</h1>
  <hr />

  <% @courses.each do |course| %>
    <h2 class = "text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    <br />
    <%= image_tag course.image, class: 'img-responsive', style: 'margin:auto' %>
    <br />
    <div class = "col-sm-8 col-xs-12">
      <%= course.description %>
    </div>

    <div class = "col-sm-4 col-xs-12 text-center">
      <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary' %>
    </div>
    <br />
    <hr class = "col-xs-8 col-xs-offset-2">
    <br class = "clr" / >
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class = "booyah-box col-xs-10 col-xs-offset-1">
  <h1><%= @course.title %></h1>
  <%= image_tag @course.image, class: 'img-responsive', style: 'margin:auto' %>
  <br />

  <div class = "col-sm-4 col-xs-12 text-center">
    <span class="label label-default">
      <% if @course.free? %>
        <%= 'free!' %>
      <% else %>
        <%= number_to_currency @course.cost %>
      <% end %>
    </span>
  
    <% if current_user && current_user == @course.user %>
      <br />
      <br />
      <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
    <% end %>

    <br />
    <br />

    <% if current_user && current_user.enrolled_in?(@course) %>
      <h3 class = "label label-info">You Are Enrolled!</h3>
    <% else %>
      <% if @course.free? %>
        <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
      <% else %>
        <%= form_tag course_enrollments_path(@course) do %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                data-amount="<%= (@course.cost * 100).to_i %>"
                data-label="Enroll Me!"
                data-email="<%= current_user.email %>">
          </script>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class = "col-sm-8 col-xs-12">
    <%= @course.description %>
  </div>

  <div class = "col-xs-12">
    <% @course.sections.rank(:row_order).each do |section| %>
      <br /><br />
      <div class = "section">
        <h3>
          <%= section.title %>
        </h3>
        <% section.lessons.rank(:row_order).each do |lesson| %>
          <div class = "col-xs-12 col-sm-6">
            <div class = "lesson text-center">
              <br />
              <%= link_to lesson_path(lesson) do %>
                <b><%= lesson.title %></b>
                <br />
                <div class = "subtitle">
                  <%= lesson.subtitle %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <br class = "clr" />
      </div>
    <% end %>  
  </div>

</div>